//ScrollReveal().reveal('.parallax',{ distance: '800px' });
ScrollReveal().reveal('.caption',{ delay: 500 });
ScrollReveal().reveal('.first_name',{ delay: 2000 });
ScrollReveal().reveal('.last_name',{ delay: 3000 });
ScrollReveal().reveal('.about_me',{ distance: '50px', delay: 500 });
ScrollReveal().reveal('.about_me1',{ distance: '50px', delay: 1000 });
ScrollReveal().reveal('.about_me2',{ distance: '50px', delay: 1500 });
ScrollReveal().reveal('.about_me3',{ distance: '50px', delay: 2000 });
ScrollReveal().reveal('.about_me4',{ distance: '50px', delay: 2500 });
ScrollReveal().reveal('.past_projects',{ distance: '50px', delay: 500 });
ScrollReveal().reveal('.past_projects_title',{ distance: '50px', delay: 1200 });
ScrollReveal().reveal('.past_projects1',{ delay: 2000 });
ScrollReveal().reveal('.past_projects2',{ delay: 2500 });
ScrollReveal().reveal('.past_projects3',{ delay: 3000 });
ScrollReveal().reveal('.past_projects4',{ delay: 3500 });
ScrollReveal().reveal('.past_projects5',{ delay: 4000 });
ScrollReveal().reveal('.past_projects6',{ delay: 4500 });